#!/usr/bin/env python3
from __future__ import annotations

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]

STATE_PATH = ROOT / "autonomy" / "state.json"
EVENTS_PATH = ROOT / "autonomy" / "events.jsonl"

SNIPPET_LIMITS = {
    "GOAL.md": 6000,
    "CURRENT.md": 14000,
    "LEDGER.md": 14000,
    "JOURNAL.md": 8000,
    "IDEAS.md": 12000,
    "BUDGET.md": 10000,
    "program.md": 12000,
}


def read_tail(path: Path, limit: int) -> str:
    if not path.exists():
        return f"[missing: {path.name}]"
    text = path.read_text(encoding="utf-8")
    if len(text) <= limit:
        return text
    return text[-limit:]


def read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def read_events_tail(limit: int = 30) -> str:
    if not EVENTS_PATH.exists():
        return "[missing: autonomy/events.jsonl]"
    lines = EVENTS_PATH.read_text(encoding="utf-8").splitlines()
    return "\n".join(lines[-limit:])


def gh_open_issues() -> str:
    cmd = [
        "gh",
        "issue",
        "list",
        "--state",
        "open",
        "--limit",
        "20",
        "--json",
        "number,title,labels,url",
    ]
    try:
        proc = subprocess.run(
            cmd,
            cwd=ROOT,
            check=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except (FileNotFoundError, subprocess.CalledProcessError) as exc:
        return f"[gh issue list unavailable: {exc}]"
    try:
        issues = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return proc.stdout.strip() or "[gh issue list returned no output]"
    if not issues:
        return "[]"
    slim = []
    for issue in issues:
        labels = [label.get("name") for label in issue.get("labels", []) if label.get("name")]
        slim.append(
            {
                "number": issue.get("number"),
                "title": issue.get("title"),
                "labels": labels,
                "url": issue.get("url"),
            }
        )
    return json.dumps(slim, indent=2)


def main() -> None:
    state = read_json(STATE_PATH)
    now = datetime.now(timezone.utc).isoformat()
    phase = state.get("phase", "unknown")
    active_job = state.get("active_job")
    spent = state.get("spent_estimate_usd")
    budget = state.get("weekly_budget_usd")

    snippets = []
    for name, limit in SNIPPET_LIMITS.items():
        snippets.append(f"## {name}\n\n{read_tail(ROOT / name, limit)}")

    prompt = f"""You are the LOCAL Codex research loop for `auto-research-2`.

This prompt is generated by `scripts/codex_research_tick.sh` and must be run locally with:

- model: `gpt-5.5`
- reasoning effort: `xhigh`
- working directory: `{ROOT}`

If you are not running as local Codex with that model/effort, stop and report the runner mismatch.

## Non-negotiable split

Research happens here in local Codex. That means source inspection, web research, hypothesis selection, code edits, controller edits, journal/ledger updates, commit/push decisions, and issue comments happen in this local session.

Hugging Face Jobs are CUDA execution substrate only. They may download data, train, infer, evaluate, and upload artifacts. They are not the researcher and must not be asked to reason around the next experiment.

GitHub Actions is only the heartbeat/checker that submits or inspects exactly one bounded HF job. It is not the research brain.

## Current state summary

- Generated: `{now}`
- Phase: `{phase}`
- Active HF job: `{json.dumps(active_job, indent=2) if active_job else "none"}`
- Estimated spend: `${spent} / ${budget}`

## One-tick assignment

Do exactly one bounded research/control-plane step.

1. Read the state and snippets below before changing anything.
2. If an HF job is active, do not launch another job. Update observability or inspect logs only if useful, then stop.
3. If phase is `blocked_budget`, do not edit the weekly cap and do not submit paid HF work. Either:
   - find a no-spend local research/code/issue improvement that helps the next tick, or
   - keep the budget issue accurate and stop.
4. If not blocked and no active job exists, choose one experiment or controller repair with a concrete expected effect on official `mAP-LocSim`.
5. Keep the AK-style harness small: prefer markdown plus tiny scripts over platform code.
6. Any meaningful ML quality decision must come from cloud CUDA plus official SSKit metric output, not local model scores.
7. Keep `CURRENT.md`, `JOURNAL.md`, `LEDGER.md`, `BUDGET.md`, `autonomy/state.json`, and GitHub issues honest as needed.
8. Before ending a mutating turn, run `scripts/verify.sh`.
9. If you mutate source/docs and verification passes, commit and push to `main`.

## Open GitHub issues

{gh_open_issues()}

## Recent autonomy events

```jsonl
{read_events_tail()}
```

{"\n\n---\n\n".join(snippets)}
"""
    print(prompt)


if __name__ == "__main__":
    main()
